openapi: 3.0.1
info:
  title: Course Management API
  description: API for managing students, courses, and enrolments
  version: 1.0.0
tags:
  - name : students
  - name : courses
  - name : enrolments

paths:
  /students:
    get:
      tags:
        - students
      summary: Get all students
      operationId: getAllStudents
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    post:
      tags:
        - students
      summary: Create a new student
      operationId: createStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Student created

  /students/{id}:
    get:
      tags:
        - students
      summary: Get student by ID
      operationId: getStudentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Student not found
    put:
      tags:
        - students
      summary: Update student
      operationId: updateStudent
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Student updated
    delete:
      tags:
        - students
      summary: Delete student
      operationId: deleteStudent
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Student deleted

  /courses:
    get:
      tags:
        - courses
      summary: Get all courses
      operationId: getAllCourses
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
    post:
      tags:
        - courses
      summary: Create a new course
      operationId: createCourse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        '201':
          description: Course created

  /courses/{id}:
    get:
      tags:
        - courses
      summary: Get course by ID
      operationId: getCourseById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        '404':
          description: Course not found
    put:
      tags:
        - courses
      summary: Update course
      operationId: updateCourse
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        '200':
          description: Course updated
    delete:
      tags:
        - courses
      summary: Delete course
      operationId: deleteCourse
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Course deleted

  /enrolments:
    get:
      tags:
        - enrolments
      summary: Get all enrolments
      operationId: getAllEnrolments
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Enrolment'
    post:
      tags:
        - enrolments
      summary: Create a new enrolment
      operationId: createEnrolment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enrolment'
      responses:
        '201':
          description: enrolment created

  /enrolments/{id}:
    get:
      tags:
        - enrolments
      summary: Get enrolment by ID
      operationId: getEnrolmentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enrolment'
        '404':
          description: enrolment not found
    put:
      tags:
        - enrolments
      summary: Update enrolment
      operationId: updateEnrolment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enrolment'
      responses:
        '200':
          description: enrolment updated
    delete:
      tags:
        - enrolments
      summary: Delete enrolment
      operationId: deleteEnrolment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Enrolment deleted

components:
  schemas:
    Student:
      type: object
      properties:
        studentId:
          type: integer
        lastName:
          type: string
        firstMidName:
          type: string
        enrolmentDate:
          type: string
          format: date
    Course:
      type: object
      properties:
        courseId:
          type: integer
        title:
          type: string
        credits:
          type: integer
    Enrolment:
      type: object
      properties:
        enrolmentId:
          type: integer
        grade:
          type: integer
        courseId:
          type: integer
        studentId:
          type: integer